/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicProductsRouteImport } from './routes/_public/products'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicCheckoutRouteImport } from './routes/_public/checkout'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as PublicProductsIdRouteImport } from './routes/_public/products.$id'
import { Route as PublicOrderSuccessOrderNumberRouteImport } from './routes/_public/order-success.$orderNumber'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/_app/users'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/_app/reports'
import { Route as AuthenticatedAppMaintenanceRouteImport } from './routes/_authenticated/_app/maintenance'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppActivityRouteImport } from './routes/_authenticated/_app/activity'
import { Route as AuthenticatedAppDevicesIndexRouteImport } from './routes/_authenticated/_app/devices.index'
import { Route as AuthenticatedAppDevicesNewRouteImport } from './routes/_authenticated/_app/devices.new'
import { Route as AuthenticatedAppDevicesIdEditRouteImport } from './routes/_authenticated/_app/devices.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsRoute = PublicProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCheckoutRoute = PublicCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicProductsIdRoute = PublicProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicProductsRoute,
} as any)
const PublicOrderSuccessOrderNumberRoute =
  PublicOrderSuccessOrderNumberRouteImport.update({
    id: '/order-success/$orderNumber',
    path: '/order-success/$orderNumber',
    getParentRoute: () => PublicRoute,
  } as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMaintenanceRoute =
  AuthenticatedAppMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppActivityRoute =
  AuthenticatedAppActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDevicesIndexRoute =
  AuthenticatedAppDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDevicesNewRoute =
  AuthenticatedAppDevicesNewRouteImport.update({
    id: '/devices/new',
    path: '/devices/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDevicesIdEditRoute =
  AuthenticatedAppDevicesIdEditRouteImport.update({
    id: '/devices/$id/edit',
    path: '/devices/$id/edit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof PublicAboutRoute
  '/checkout': typeof PublicCheckoutRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/privacy': typeof PublicPrivacyRoute
  '/products': typeof PublicProductsRouteWithChildren
  '/terms': typeof PublicTermsRoute
  '/activity': typeof AuthenticatedAppActivityRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/reports': typeof AuthenticatedAppReportsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/users': typeof AuthenticatedAppUsersRoute
  '/order-success/$orderNumber': typeof PublicOrderSuccessOrderNumberRoute
  '/products/$id': typeof PublicProductsIdRoute
  '/devices/new': typeof AuthenticatedAppDevicesNewRoute
  '/devices/': typeof AuthenticatedAppDevicesIndexRoute
  '/devices/$id/edit': typeof AuthenticatedAppDevicesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof PublicAboutRoute
  '/checkout': typeof PublicCheckoutRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/privacy': typeof PublicPrivacyRoute
  '/products': typeof PublicProductsRouteWithChildren
  '/terms': typeof PublicTermsRoute
  '/activity': typeof AuthenticatedAppActivityRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/reports': typeof AuthenticatedAppReportsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/users': typeof AuthenticatedAppUsersRoute
  '/order-success/$orderNumber': typeof PublicOrderSuccessOrderNumberRoute
  '/products/$id': typeof PublicProductsIdRoute
  '/devices/new': typeof AuthenticatedAppDevicesNewRoute
  '/devices': typeof AuthenticatedAppDevicesIndexRoute
  '/devices/$id/edit': typeof AuthenticatedAppDevicesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/checkout': typeof PublicCheckoutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/products': typeof PublicProductsRouteWithChildren
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/_app/activity': typeof AuthenticatedAppActivityRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/_authenticated/_app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/_app/users': typeof AuthenticatedAppUsersRoute
  '/_public/order-success/$orderNumber': typeof PublicOrderSuccessOrderNumberRoute
  '/_public/products/$id': typeof PublicProductsIdRoute
  '/_authenticated/_app/devices/new': typeof AuthenticatedAppDevicesNewRoute
  '/_authenticated/_app/devices/': typeof AuthenticatedAppDevicesIndexRoute
  '/_authenticated/_app/devices/$id/edit': typeof AuthenticatedAppDevicesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/products'
    | '/terms'
    | '/activity'
    | '/dashboard'
    | '/maintenance'
    | '/reports'
    | '/settings'
    | '/users'
    | '/order-success/$orderNumber'
    | '/products/$id'
    | '/devices/new'
    | '/devices/'
    | '/devices/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/products'
    | '/terms'
    | '/activity'
    | '/dashboard'
    | '/maintenance'
    | '/reports'
    | '/settings'
    | '/users'
    | '/order-success/$orderNumber'
    | '/products/$id'
    | '/devices/new'
    | '/devices'
    | '/devices/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/auth'
    | '/_authenticated/_app'
    | '/_public/about'
    | '/_public/checkout'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/privacy'
    | '/_public/products'
    | '/_public/terms'
    | '/_public/'
    | '/_authenticated/_app/activity'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/maintenance'
    | '/_authenticated/_app/reports'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_app/users'
    | '/_public/order-success/$orderNumber'
    | '/_public/products/$id'
    | '/_authenticated/_app/devices/new'
    | '/_authenticated/_app/devices/'
    | '/_authenticated/_app/devices/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products': {
      id: '/_public/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PublicProductsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/checkout': {
      id: '/_public/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PublicCheckoutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/products/$id': {
      id: '/_public/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof PublicProductsIdRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/order-success/$orderNumber': {
      id: '/_public/order-success/$orderNumber'
      path: '/order-success/$orderNumber'
      fullPath: '/order-success/$orderNumber'
      preLoaderRoute: typeof PublicOrderSuccessOrderNumberRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_app/users': {
      id: '/_authenticated/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/reports': {
      id: '/_authenticated/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/maintenance': {
      id: '/_authenticated/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedAppMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/activity': {
      id: '/_authenticated/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedAppActivityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/devices/': {
      id: '/_authenticated/_app/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AuthenticatedAppDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/devices/new': {
      id: '/_authenticated/_app/devices/new'
      path: '/devices/new'
      fullPath: '/devices/new'
      preLoaderRoute: typeof AuthenticatedAppDevicesNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/devices/$id/edit': {
      id: '/_authenticated/_app/devices/$id/edit'
      path: '/devices/$id/edit'
      fullPath: '/devices/$id/edit'
      preLoaderRoute: typeof AuthenticatedAppDevicesIdEditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppActivityRoute: typeof AuthenticatedAppActivityRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppMaintenanceRoute: typeof AuthenticatedAppMaintenanceRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppDevicesNewRoute: typeof AuthenticatedAppDevicesNewRoute
  AuthenticatedAppDevicesIndexRoute: typeof AuthenticatedAppDevicesIndexRoute
  AuthenticatedAppDevicesIdEditRoute: typeof AuthenticatedAppDevicesIdEditRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppActivityRoute: AuthenticatedAppActivityRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppMaintenanceRoute: AuthenticatedAppMaintenanceRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppDevicesNewRoute: AuthenticatedAppDevicesNewRoute,
  AuthenticatedAppDevicesIndexRoute: AuthenticatedAppDevicesIndexRoute,
  AuthenticatedAppDevicesIdEditRoute: AuthenticatedAppDevicesIdEditRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicProductsRouteChildren {
  PublicProductsIdRoute: typeof PublicProductsIdRoute
}

const PublicProductsRouteChildren: PublicProductsRouteChildren = {
  PublicProductsIdRoute: PublicProductsIdRoute,
}

const PublicProductsRouteWithChildren = PublicProductsRoute._addFileChildren(
  PublicProductsRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicCheckoutRoute: typeof PublicCheckoutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicProductsRoute: typeof PublicProductsRouteWithChildren
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicOrderSuccessOrderNumberRoute: typeof PublicOrderSuccessOrderNumberRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicCheckoutRoute: PublicCheckoutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicProductsRoute: PublicProductsRouteWithChildren,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicOrderSuccessOrderNumberRoute: PublicOrderSuccessOrderNumberRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
