/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicProductsRouteImport } from './routes/_public/products'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicCheckoutRouteImport } from './routes/_public/checkout'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedStaffRouteRouteImport } from './routes/_authenticated/staff/route'
import { Route as AuthenticatedCustomerRouteRouteImport } from './routes/_authenticated/customer/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as PublicProductsIndexRouteImport } from './routes/_public/products.index'
import { Route as PublicProductsIdRouteImport } from './routes/_public/products.$id'
import { Route as PublicOrderSuccessOrderNumberRouteImport } from './routes/_public/order-success.$orderNumber'
import { Route as AuthenticatedStaffSettingsRouteImport } from './routes/_authenticated/staff/settings'
import { Route as AuthenticatedStaffReportsRouteImport } from './routes/_authenticated/staff/reports'
import { Route as AuthenticatedStaffOrdersRouteImport } from './routes/_authenticated/staff/orders'
import { Route as AuthenticatedStaffMaintenanceRouteImport } from './routes/_authenticated/staff/maintenance'
import { Route as AuthenticatedStaffDashboardRouteImport } from './routes/_authenticated/staff/dashboard'
import { Route as AuthenticatedStaffAiRouteImport } from './routes/_authenticated/staff/ai'
import { Route as AuthenticatedCustomerSettingsRouteImport } from './routes/_authenticated/customer/settings'
import { Route as AuthenticatedCustomerDashboardRouteImport } from './routes/_authenticated/customer/dashboard'
import { Route as AuthenticatedCustomerAiRouteImport } from './routes/_authenticated/customer/ai'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminMaintenanceRouteImport } from './routes/_authenticated/admin/maintenance'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin/ai'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin/activity'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/_app/users'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/_app/reports'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/_app/orders'
import { Route as AuthenticatedAppMaintenanceRouteImport } from './routes/_authenticated/_app/maintenance'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppActivityRouteImport } from './routes/_authenticated/_app/activity'
import { Route as AuthenticatedStaffDevicesIndexRouteImport } from './routes/_authenticated/staff/devices.index'
import { Route as AuthenticatedAdminDevicesIndexRouteImport } from './routes/_authenticated/admin/devices.index'
import { Route as AuthenticatedAppDevicesIndexRouteImport } from './routes/_authenticated/_app/devices.index'
import { Route as AuthenticatedAdminDevicesNewRouteImport } from './routes/_authenticated/admin/devices.new'
import { Route as AuthenticatedAppDevicesNewRouteImport } from './routes/_authenticated/_app/devices.new'
import { Route as AuthenticatedAdminDevicesIdEditRouteImport } from './routes/_authenticated/admin/devices.$id.edit'
import { Route as AuthenticatedAppDevicesIdEditRouteImport } from './routes/_authenticated/_app/devices.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsRoute = PublicProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCheckoutRoute = PublicCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRouteRoute = AuthenticatedStaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerRouteRoute =
  AuthenticatedCustomerRouteRouteImport.update({
    id: '/customer',
    path: '/customer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicProductsRoute,
} as any)
const PublicProductsIdRoute = PublicProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicProductsRoute,
} as any)
const PublicOrderSuccessOrderNumberRoute =
  PublicOrderSuccessOrderNumberRouteImport.update({
    id: '/order-success/$orderNumber',
    path: '/order-success/$orderNumber',
    getParentRoute: () => PublicRoute,
  } as any)
const AuthenticatedStaffSettingsRoute =
  AuthenticatedStaffSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedStaffReportsRoute =
  AuthenticatedStaffReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedStaffOrdersRoute =
  AuthenticatedStaffOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedStaffMaintenanceRoute =
  AuthenticatedStaffMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedStaffDashboardRoute =
  AuthenticatedStaffDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedStaffAiRoute = AuthenticatedStaffAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedStaffRouteRoute,
} as any)
const AuthenticatedCustomerSettingsRoute =
  AuthenticatedCustomerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCustomerRouteRoute,
  } as any)
const AuthenticatedCustomerDashboardRoute =
  AuthenticatedCustomerDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCustomerRouteRoute,
  } as any)
const AuthenticatedCustomerAiRoute = AuthenticatedCustomerAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedCustomerRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMaintenanceRoute =
  AuthenticatedAdminMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMaintenanceRoute =
  AuthenticatedAppMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppActivityRoute =
  AuthenticatedAppActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedStaffDevicesIndexRoute =
  AuthenticatedStaffDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedAdminDevicesIndexRoute =
  AuthenticatedAdminDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppDevicesIndexRoute =
  AuthenticatedAppDevicesIndexRouteImport.update({
    id: '/devices/',
    path: '/devices/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminDevicesNewRoute =
  AuthenticatedAdminDevicesNewRouteImport.update({
    id: '/devices/new',
    path: '/devices/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppDevicesNewRoute =
  AuthenticatedAppDevicesNewRouteImport.update({
    id: '/devices/new',
    path: '/devices/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminDevicesIdEditRoute =
  AuthenticatedAdminDevicesIdEditRouteImport.update({
    id: '/devices/$id/edit',
    path: '/devices/$id/edit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppDevicesIdEditRoute =
  AuthenticatedAppDevicesIdEditRouteImport.update({
    id: '/devices/$id/edit',
    path: '/devices/$id/edit',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/customer': typeof AuthenticatedCustomerRouteRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/checkout': typeof PublicCheckoutRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/privacy': typeof PublicPrivacyRoute
  '/products': typeof PublicProductsRouteWithChildren
  '/terms': typeof PublicTermsRoute
  '/activity': typeof AuthenticatedAppActivityRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/orders': typeof AuthenticatedAppOrdersRoute
  '/reports': typeof AuthenticatedAppReportsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/users': typeof AuthenticatedAppUsersRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/customer/ai': typeof AuthenticatedCustomerAiRoute
  '/customer/dashboard': typeof AuthenticatedCustomerDashboardRoute
  '/customer/settings': typeof AuthenticatedCustomerSettingsRoute
  '/staff/ai': typeof AuthenticatedStaffAiRoute
  '/staff/dashboard': typeof AuthenticatedStaffDashboardRoute
  '/staff/maintenance': typeof AuthenticatedStaffMaintenanceRoute
  '/staff/orders': typeof AuthenticatedStaffOrdersRoute
  '/staff/reports': typeof AuthenticatedStaffReportsRoute
  '/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/order-success/$orderNumber': typeof PublicOrderSuccessOrderNumberRoute
  '/products/$id': typeof PublicProductsIdRoute
  '/products/': typeof PublicProductsIndexRoute
  '/devices/new': typeof AuthenticatedAppDevicesNewRoute
  '/admin/devices/new': typeof AuthenticatedAdminDevicesNewRoute
  '/devices/': typeof AuthenticatedAppDevicesIndexRoute
  '/admin/devices/': typeof AuthenticatedAdminDevicesIndexRoute
  '/staff/devices/': typeof AuthenticatedStaffDevicesIndexRoute
  '/devices/$id/edit': typeof AuthenticatedAppDevicesIdEditRoute
  '/admin/devices/$id/edit': typeof AuthenticatedAdminDevicesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/customer': typeof AuthenticatedCustomerRouteRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/checkout': typeof PublicCheckoutRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/activity': typeof AuthenticatedAppActivityRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/orders': typeof AuthenticatedAppOrdersRoute
  '/reports': typeof AuthenticatedAppReportsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/users': typeof AuthenticatedAppUsersRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/customer/ai': typeof AuthenticatedCustomerAiRoute
  '/customer/dashboard': typeof AuthenticatedCustomerDashboardRoute
  '/customer/settings': typeof AuthenticatedCustomerSettingsRoute
  '/staff/ai': typeof AuthenticatedStaffAiRoute
  '/staff/dashboard': typeof AuthenticatedStaffDashboardRoute
  '/staff/maintenance': typeof AuthenticatedStaffMaintenanceRoute
  '/staff/orders': typeof AuthenticatedStaffOrdersRoute
  '/staff/reports': typeof AuthenticatedStaffReportsRoute
  '/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/order-success/$orderNumber': typeof PublicOrderSuccessOrderNumberRoute
  '/products/$id': typeof PublicProductsIdRoute
  '/products': typeof PublicProductsIndexRoute
  '/devices/new': typeof AuthenticatedAppDevicesNewRoute
  '/admin/devices/new': typeof AuthenticatedAdminDevicesNewRoute
  '/devices': typeof AuthenticatedAppDevicesIndexRoute
  '/admin/devices': typeof AuthenticatedAdminDevicesIndexRoute
  '/staff/devices': typeof AuthenticatedStaffDevicesIndexRoute
  '/devices/$id/edit': typeof AuthenticatedAppDevicesIdEditRoute
  '/admin/devices/$id/edit': typeof AuthenticatedAdminDevicesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/customer': typeof AuthenticatedCustomerRouteRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/checkout': typeof PublicCheckoutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/products': typeof PublicProductsRouteWithChildren
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/_app/activity': typeof AuthenticatedAppActivityRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/maintenance': typeof AuthenticatedAppMaintenanceRoute
  '/_authenticated/_app/orders': typeof AuthenticatedAppOrdersRoute
  '/_authenticated/_app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/_app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/customer/ai': typeof AuthenticatedCustomerAiRoute
  '/_authenticated/customer/dashboard': typeof AuthenticatedCustomerDashboardRoute
  '/_authenticated/customer/settings': typeof AuthenticatedCustomerSettingsRoute
  '/_authenticated/staff/ai': typeof AuthenticatedStaffAiRoute
  '/_authenticated/staff/dashboard': typeof AuthenticatedStaffDashboardRoute
  '/_authenticated/staff/maintenance': typeof AuthenticatedStaffMaintenanceRoute
  '/_authenticated/staff/orders': typeof AuthenticatedStaffOrdersRoute
  '/_authenticated/staff/reports': typeof AuthenticatedStaffReportsRoute
  '/_authenticated/staff/settings': typeof AuthenticatedStaffSettingsRoute
  '/_public/order-success/$orderNumber': typeof PublicOrderSuccessOrderNumberRoute
  '/_public/products/$id': typeof PublicProductsIdRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/_authenticated/_app/devices/new': typeof AuthenticatedAppDevicesNewRoute
  '/_authenticated/admin/devices/new': typeof AuthenticatedAdminDevicesNewRoute
  '/_authenticated/_app/devices/': typeof AuthenticatedAppDevicesIndexRoute
  '/_authenticated/admin/devices/': typeof AuthenticatedAdminDevicesIndexRoute
  '/_authenticated/staff/devices/': typeof AuthenticatedStaffDevicesIndexRoute
  '/_authenticated/_app/devices/$id/edit': typeof AuthenticatedAppDevicesIdEditRoute
  '/_authenticated/admin/devices/$id/edit': typeof AuthenticatedAdminDevicesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/customer'
    | '/staff'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/products'
    | '/terms'
    | '/activity'
    | '/dashboard'
    | '/maintenance'
    | '/orders'
    | '/reports'
    | '/settings'
    | '/users'
    | '/admin/activity'
    | '/admin/ai'
    | '/admin/dashboard'
    | '/admin/maintenance'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/ai'
    | '/customer/dashboard'
    | '/customer/settings'
    | '/staff/ai'
    | '/staff/dashboard'
    | '/staff/maintenance'
    | '/staff/orders'
    | '/staff/reports'
    | '/staff/settings'
    | '/order-success/$orderNumber'
    | '/products/$id'
    | '/products/'
    | '/devices/new'
    | '/admin/devices/new'
    | '/devices/'
    | '/admin/devices/'
    | '/staff/devices/'
    | '/devices/$id/edit'
    | '/admin/devices/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/customer'
    | '/staff'
    | '/about'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/activity'
    | '/dashboard'
    | '/maintenance'
    | '/orders'
    | '/reports'
    | '/settings'
    | '/users'
    | '/admin/activity'
    | '/admin/ai'
    | '/admin/dashboard'
    | '/admin/maintenance'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/ai'
    | '/customer/dashboard'
    | '/customer/settings'
    | '/staff/ai'
    | '/staff/dashboard'
    | '/staff/maintenance'
    | '/staff/orders'
    | '/staff/reports'
    | '/staff/settings'
    | '/order-success/$orderNumber'
    | '/products/$id'
    | '/products'
    | '/devices/new'
    | '/admin/devices/new'
    | '/devices'
    | '/admin/devices'
    | '/staff/devices'
    | '/devices/$id/edit'
    | '/admin/devices/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/customer'
    | '/_authenticated/staff'
    | '/_authenticated/_app'
    | '/_public/about'
    | '/_public/checkout'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/privacy'
    | '/_public/products'
    | '/_public/terms'
    | '/_public/'
    | '/_authenticated/_app/activity'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/maintenance'
    | '/_authenticated/_app/orders'
    | '/_authenticated/_app/reports'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_app/users'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/maintenance'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/customer/ai'
    | '/_authenticated/customer/dashboard'
    | '/_authenticated/customer/settings'
    | '/_authenticated/staff/ai'
    | '/_authenticated/staff/dashboard'
    | '/_authenticated/staff/maintenance'
    | '/_authenticated/staff/orders'
    | '/_authenticated/staff/reports'
    | '/_authenticated/staff/settings'
    | '/_public/order-success/$orderNumber'
    | '/_public/products/$id'
    | '/_public/products/'
    | '/_authenticated/_app/devices/new'
    | '/_authenticated/admin/devices/new'
    | '/_authenticated/_app/devices/'
    | '/_authenticated/admin/devices/'
    | '/_authenticated/staff/devices/'
    | '/_authenticated/_app/devices/$id/edit'
    | '/_authenticated/admin/devices/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products': {
      id: '/_public/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PublicProductsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/checkout': {
      id: '/_public/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PublicCheckoutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer': {
      id: '/_authenticated/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AuthenticatedCustomerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/products/$id': {
      id: '/_public/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof PublicProductsIdRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/order-success/$orderNumber': {
      id: '/_public/order-success/$orderNumber'
      path: '/order-success/$orderNumber'
      fullPath: '/order-success/$orderNumber'
      preLoaderRoute: typeof PublicOrderSuccessOrderNumberRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/staff/settings': {
      id: '/_authenticated/staff/settings'
      path: '/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof AuthenticatedStaffSettingsRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/staff/reports': {
      id: '/_authenticated/staff/reports'
      path: '/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof AuthenticatedStaffReportsRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/staff/orders': {
      id: '/_authenticated/staff/orders'
      path: '/orders'
      fullPath: '/staff/orders'
      preLoaderRoute: typeof AuthenticatedStaffOrdersRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/staff/maintenance': {
      id: '/_authenticated/staff/maintenance'
      path: '/maintenance'
      fullPath: '/staff/maintenance'
      preLoaderRoute: typeof AuthenticatedStaffMaintenanceRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/staff/dashboard': {
      id: '/_authenticated/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof AuthenticatedStaffDashboardRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/staff/ai': {
      id: '/_authenticated/staff/ai'
      path: '/ai'
      fullPath: '/staff/ai'
      preLoaderRoute: typeof AuthenticatedStaffAiRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/customer/settings': {
      id: '/_authenticated/customer/settings'
      path: '/settings'
      fullPath: '/customer/settings'
      preLoaderRoute: typeof AuthenticatedCustomerSettingsRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/customer/dashboard': {
      id: '/_authenticated/customer/dashboard'
      path: '/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof AuthenticatedCustomerDashboardRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/customer/ai': {
      id: '/_authenticated/customer/ai'
      path: '/ai'
      fullPath: '/customer/ai'
      preLoaderRoute: typeof AuthenticatedCustomerAiRouteImport
      parentRoute: typeof AuthenticatedCustomerRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/maintenance': {
      id: '/_authenticated/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AuthenticatedAdminMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_app/users': {
      id: '/_authenticated/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/reports': {
      id: '/_authenticated/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/orders': {
      id: '/_authenticated/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/maintenance': {
      id: '/_authenticated/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedAppMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/activity': {
      id: '/_authenticated/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedAppActivityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/staff/devices/': {
      id: '/_authenticated/staff/devices/'
      path: '/devices'
      fullPath: '/staff/devices/'
      preLoaderRoute: typeof AuthenticatedStaffDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/admin/devices/': {
      id: '/_authenticated/admin/devices/'
      path: '/devices'
      fullPath: '/admin/devices/'
      preLoaderRoute: typeof AuthenticatedAdminDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_app/devices/': {
      id: '/_authenticated/_app/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AuthenticatedAppDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/devices/new': {
      id: '/_authenticated/admin/devices/new'
      path: '/devices/new'
      fullPath: '/admin/devices/new'
      preLoaderRoute: typeof AuthenticatedAdminDevicesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_app/devices/new': {
      id: '/_authenticated/_app/devices/new'
      path: '/devices/new'
      fullPath: '/devices/new'
      preLoaderRoute: typeof AuthenticatedAppDevicesNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/devices/$id/edit': {
      id: '/_authenticated/admin/devices/$id/edit'
      path: '/devices/$id/edit'
      fullPath: '/admin/devices/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminDevicesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_app/devices/$id/edit': {
      id: '/_authenticated/_app/devices/$id/edit'
      path: '/devices/$id/edit'
      fullPath: '/devices/$id/edit'
      preLoaderRoute: typeof AuthenticatedAppDevicesIdEditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminMaintenanceRoute: typeof AuthenticatedAdminMaintenanceRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminDevicesNewRoute: typeof AuthenticatedAdminDevicesNewRoute
  AuthenticatedAdminDevicesIndexRoute: typeof AuthenticatedAdminDevicesIndexRoute
  AuthenticatedAdminDevicesIdEditRoute: typeof AuthenticatedAdminDevicesIdEditRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
    AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminMaintenanceRoute: AuthenticatedAdminMaintenanceRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminDevicesNewRoute: AuthenticatedAdminDevicesNewRoute,
    AuthenticatedAdminDevicesIndexRoute: AuthenticatedAdminDevicesIndexRoute,
    AuthenticatedAdminDevicesIdEditRoute: AuthenticatedAdminDevicesIdEditRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCustomerRouteRouteChildren {
  AuthenticatedCustomerAiRoute: typeof AuthenticatedCustomerAiRoute
  AuthenticatedCustomerDashboardRoute: typeof AuthenticatedCustomerDashboardRoute
  AuthenticatedCustomerSettingsRoute: typeof AuthenticatedCustomerSettingsRoute
}

const AuthenticatedCustomerRouteRouteChildren: AuthenticatedCustomerRouteRouteChildren =
  {
    AuthenticatedCustomerAiRoute: AuthenticatedCustomerAiRoute,
    AuthenticatedCustomerDashboardRoute: AuthenticatedCustomerDashboardRoute,
    AuthenticatedCustomerSettingsRoute: AuthenticatedCustomerSettingsRoute,
  }

const AuthenticatedCustomerRouteRouteWithChildren =
  AuthenticatedCustomerRouteRoute._addFileChildren(
    AuthenticatedCustomerRouteRouteChildren,
  )

interface AuthenticatedStaffRouteRouteChildren {
  AuthenticatedStaffAiRoute: typeof AuthenticatedStaffAiRoute
  AuthenticatedStaffDashboardRoute: typeof AuthenticatedStaffDashboardRoute
  AuthenticatedStaffMaintenanceRoute: typeof AuthenticatedStaffMaintenanceRoute
  AuthenticatedStaffOrdersRoute: typeof AuthenticatedStaffOrdersRoute
  AuthenticatedStaffReportsRoute: typeof AuthenticatedStaffReportsRoute
  AuthenticatedStaffSettingsRoute: typeof AuthenticatedStaffSettingsRoute
  AuthenticatedStaffDevicesIndexRoute: typeof AuthenticatedStaffDevicesIndexRoute
}

const AuthenticatedStaffRouteRouteChildren: AuthenticatedStaffRouteRouteChildren =
  {
    AuthenticatedStaffAiRoute: AuthenticatedStaffAiRoute,
    AuthenticatedStaffDashboardRoute: AuthenticatedStaffDashboardRoute,
    AuthenticatedStaffMaintenanceRoute: AuthenticatedStaffMaintenanceRoute,
    AuthenticatedStaffOrdersRoute: AuthenticatedStaffOrdersRoute,
    AuthenticatedStaffReportsRoute: AuthenticatedStaffReportsRoute,
    AuthenticatedStaffSettingsRoute: AuthenticatedStaffSettingsRoute,
    AuthenticatedStaffDevicesIndexRoute: AuthenticatedStaffDevicesIndexRoute,
  }

const AuthenticatedStaffRouteRouteWithChildren =
  AuthenticatedStaffRouteRoute._addFileChildren(
    AuthenticatedStaffRouteRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppActivityRoute: typeof AuthenticatedAppActivityRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppMaintenanceRoute: typeof AuthenticatedAppMaintenanceRoute
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppDevicesNewRoute: typeof AuthenticatedAppDevicesNewRoute
  AuthenticatedAppDevicesIndexRoute: typeof AuthenticatedAppDevicesIndexRoute
  AuthenticatedAppDevicesIdEditRoute: typeof AuthenticatedAppDevicesIdEditRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppActivityRoute: AuthenticatedAppActivityRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppMaintenanceRoute: AuthenticatedAppMaintenanceRoute,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppDevicesNewRoute: AuthenticatedAppDevicesNewRoute,
  AuthenticatedAppDevicesIndexRoute: AuthenticatedAppDevicesIndexRoute,
  AuthenticatedAppDevicesIdEditRoute: AuthenticatedAppDevicesIdEditRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCustomerRouteRoute: typeof AuthenticatedCustomerRouteRouteWithChildren
  AuthenticatedStaffRouteRoute: typeof AuthenticatedStaffRouteRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCustomerRouteRoute: AuthenticatedCustomerRouteRouteWithChildren,
  AuthenticatedStaffRouteRoute: AuthenticatedStaffRouteRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicProductsRouteChildren {
  PublicProductsIdRoute: typeof PublicProductsIdRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
}

const PublicProductsRouteChildren: PublicProductsRouteChildren = {
  PublicProductsIdRoute: PublicProductsIdRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
}

const PublicProductsRouteWithChildren = PublicProductsRoute._addFileChildren(
  PublicProductsRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicCheckoutRoute: typeof PublicCheckoutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicProductsRoute: typeof PublicProductsRouteWithChildren
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicOrderSuccessOrderNumberRoute: typeof PublicOrderSuccessOrderNumberRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicCheckoutRoute: PublicCheckoutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicProductsRoute: PublicProductsRouteWithChildren,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicOrderSuccessOrderNumberRoute: PublicOrderSuccessOrderNumberRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
